### ISSUE TITLE
code run multiple times

### ISSUE THREAD

**Issue by akhtarongraph** [jmettraux/rufus-scheduler#153]
```ruby
require 'rubygems'
require 'rufus/scheduler'

scheduler = Rufus::Scheduler.new

scheduler.cron '15 22 * * *' do
  students = Student.all
  students.each do |student|
    if student.has_active_account? && student.do_activity
      UserMailer.activity_mail(student)
    end
  end
end
```

when i using this code  "UserMailer.activity_mail(student)" is called four times. Please help me.

**Comment by jmettraux** [comment]
Well, if you have 4 students who all have an active account and all yield a trueish value for `#do_activity` then I think it's normal to have `UserMailer.activity_mail(student)` getting called 4 times.

On the other hand, are you sure you don't have 4 Ruby processes running?

In what context are you running this? If the context is Ruby on Rails, on what server (Webrick, Thin, Unicorn, ...) are you running your application?

Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html it will help you (and me) a lot.

Closing since it is very probably not a rufus-scheduler issue but a misconfiguration on your side (but I'll still try to help you).

**Comment by akhtarongraph** [comment]
We are using unicorn server, ngnix and rails 4.
The problem is that Each student is getting 4 mails. I have 10 student the 10 students get 4 mail each at same time.

**Comment by jmettraux** [comment]
Please read on from https://github.com/jmettraux/rufus-scheduler#lockfile--mylockfiletxt

You're probably having 4 Ruby processes with a rufus-scheduler instance each. Hence the 4 emails.
