### ISSUE TITLE
How can I start rufus?

### ISSUE THREAD

**Issue by deyvid5** [jmettraux/rufus-scheduler#155]
Siily question, but needed to be asked.

```ruby
# My code

require 'rubygems'
require 'rake'
require 'rufus-scheduler'

load File.join(Rails.root, 'Rakefile')

ENV['host']='localhost'
ENV['port']='110'
#ENV['ssl']='SSL'
ENV['username']='xxx'
ENV['password']='xxx'
ENV['RAILS_ENV']='production'

scheduler = Rufus::Scheduler.new

scheduler.interval '1m' do
  task = Rake.application['redmine:email:receive_pop3']
  task.reenable
  task.invoke 
end
```

How can I be assured it's even started?

**Comment by jmettraux** [comment]
> How can I be assured it's even started?

How do you assure that the code below is even started?

```ruby
require 'rubygems'
require 'rufus-scheduler'

scheduler = Rufus::Scheduler.new

scheduler.interval '1s' do
  puts "I assure you! It's #{Time.now}"
end

scheduler.join # prevents the standalone script from exiting and killing the scheduler
```

**Comment by jmettraux** [comment]
Maybe, reading the friendly manual helps: https://github.com/jmettraux/rufus-scheduler#so-rails

**Comment by deyvid5** [comment]
Yes, exactly. I have this code into config/initalizers/rufus.rb
Of course, gem is installed. Is there sth to type in console, to start the schedule task to run "in the background"?

**Comment by deyvid5** [comment]
I'm totally new to Ruby. I don't even know where to find this 

I assure you! It's #{Time.now}

**Comment by deyvid5** [comment]
Is there any command to type info command line to wait for this alert?

**Comment by jmettraux** [comment]
Please read http://guides.rubyonrails.org/debugging_rails_applications.html#what-is-the-logger-questionmark to learn about rails loggers.

> Is there sth to type in console, to start the schedule task to run "in the background"?

No, Rails will run the initializer which will start the scheduler.

You can simplify your testing by jumping just a little bit and try a `config/initializers/rufus.rb` that contains

```ruby
require 'rubygems'
require 'rufus-scheduler'

scheduler = Rufus::Scheduler.new

scheduler.interval '1s' do
  Logger.debug "I assure you! It's #{Time.now}"
end
```

Note that this furiously resembles the code in https://github.com/jmettraux/rufus-scheduler#so-rails which I linked you to.

> Is there any command to type info command line to wait for this alert?

this could help (but replace `xxx.log` by the real log file name (Sorry I haven't used Rails since 2012)).

`tail -f log/xxx.log | grep "I assure you"`

Please be aware that I'll do my best to help you, but that I cannot possibly teach Ruby (and especially Rails) out of pure kindness. http://www.catb.org/esr/faqs/smart-questions.html

**Comment by deyvid5** [comment]
Thank you!~

I quess my task is not working at all (the mail one). Trying to do it since 3 days, no success. Starting to getting on my nerves...
