### ISSUE TITLE
BSON::InvalidKey

### ISSUE THREAD

**Issue by cuongpro2511** [jmettraux/rufus-scheduler#162]
Please help me solve this problems:
```
  #My code

  def expired_at=(datetime)
    datetime = Time.zone.parse(datetime) if datetime.class == String && !datetime.empty?
    if expired_at
      expired_at
    else
      if datetime > Time.zone.now
        scheduler = Rufus::Scheduler.new
        begin
          scheduler.at (datetime).strftime("%Y/%m/%d %H:%M") do
            self.update_attributes(:finished => true )
          end
        rescue
        end
      else
        self[:finished] = true
      end
      self[:expired_at] = datetime
    end
 end
```

error code: 

```
70167784245640 rufus-scheduler intercepted an error:
10:45:00 Rails.1 |    70167784245640   job:
10:45:00 Rails.1 |    70167784245640     Rufus::Scheduler::AtJob "2015/08/25 10:45" {}
10:45:00 Rails.1 |    70167784245640   error:
10:45:00 Rails.1 |    70167784245640     70167784245640
10:45:00 Rails.1 |    70167784245640     BSON::InvalidKey
10:45:00 Rails.1 |    70167784245640     Time instances are not allowed as keys in a BSON document
```

I'm stuck in this problem, because that not happens all. I checked many times and that sometimes happen.

**Comment by jmettraux** [comment]
Hello,

it's quite obvious:
```
10:45:00 Rails.1 | 70167784245640  BSON::InvalidKey
10:45:00 Rails.1 | 70167784245640  Time instances are not allowed as keys in a BSON document
```
It's probably triggered by your
```ruby
self[:expired_at] = datetime
```
Since Time instances are not allowed in BSON, try with something like
```ruby
self[:expired_at] = datetime.to_s
```

Closing since it's not a rufus-scheduler issue at all.

**Warning**

You are shooting yourself in the foot with your code. It's bad to instantiate a new rufus-scheduler instance each time you call `expired_at=`. Do you realize that this creates a new Thread of execution for each call?

You'd better read the rufus-scheduler README at https://github.com/jmettraux/rufus-scheduler#so-rails and set up a single rufus-scheduler instance at Rails start time, then have a single rufus-scheduler scheduler that checks, say every hour, for expired items and updates them accordingly.

Best regards, good luck.
