### ISSUE TITLE
Maybe there should be a web UI to see the jobs

### ISSUE THREAD

**Issue by lanjingyu** [jmettraux/rufus-scheduler#185]
Just like the sidekiq web UI , a jobs list or something that can monitor the jobs. 
Because I don't know when that schedule job run, the last time it run, how many times it run or something like that. 
Maybe this is not an issue, but a request?

**Comment by jmettraux** [comment]
Please read the documentation: https://github.com/jmettraux/rufus-scheduler#looking-up-jobs
It explains you how to list jobs and get details about them.

Regarding a web UI, I consider it out of scope, rufus-scheduler is a pure library, not a Ruby on Rails plugin or a Rack middleware. If I had to make a web UI I'd make it Sinatra based and then everyone would complain because they want something Ruby on Rails based.

Furthermore, I don't have the time nor the motivation to do it.

Best regards.
