### ISSUE TITLE
QUESTION: How can I prevent duplicate jobs from appearing in the queue?

### ISSUE THREAD

**Issue by dugjason** [jmettraux/rufus-scheduler#192]
I'd like to find out how to prevent a job from being enqueued if another instance of that job is already enqueued.

I've tried experimenting with the [Scheduler#jobs](https://github.com/jmettraux/rufus-scheduler#schedulerjobstag--tags--x) stuff, but had no luck in returning the number of jobs with a given tag that are currently in my Redis queue. 

Any suggestions?

**Comment by jmettraux** [comment]
Hello,

> I'd like to find out how to prevent a job from being enqueued if another instance of that job is already enqueued.

Maybe you're having multiple instance of the scheduler

> I've tried experimenting with the Scheduler#jobs stuff, but had no luck in returning the number of jobs with a given tag that are currently in my Redis queue.

I don't understand that, especially since rufus-scheduler in itself has nothing to do with Redis. "had no luck", what does that really mean? The rufus-scheduler Scheduler#jobs will not return the number of jobs with a given tag that are currently in Redis, rufus-scheduler will not magically query Redis for you.

> Any suggestions?

1)

Most of the scheduling methods (see https://github.com/jmettraux/rufus-scheduler#schedule_x-vs-x ) return a job id, like `"cron_1452633002.2906969_3882117664949439483"`. You could store that job id in Redis to known if the what you have in Redis is still matching an existing job in your rufus-scheduler instance.

2)

You could use a tag, shared by the piece of information stored in Redis and the rufus-scheduler instance. https://github.com/jmettraux/rufus-scheduler#schedulerjobstag--tags--x
You can then query rufus-scheduler to determine if the job is still present in there.

Does that help?

Closing the issue but not the conversation.

Best regards.

**Comment by dugjason** [comment]
Yes, thanks. Very helpful. Right now I only use rufus-scheduler to schedule when my recurring jobs are put into a Redis queue to be processed by Resque; this seems to be where the confusion comes from. 
I'll interface directly with Redis to pull this stuff out. This was totally down to user error. Thanks again!

**Comment by dugjason** [comment]
Just for reference, this is what I was looking to achieve:

```
require 'rufus-scheduler'

scheduler = Rufus::Scheduler.singleton

scheduler.every '10m', tag: 'UpdateMetricsJob' do
  jobs = []
  Resque.peek(:default, 0, 1000).find_all { |job| jobs.push job['args'][0]['job_class'] }
  UpdateMetricsJob.perform_later unless jobs.include? "UpdateMetricsJob"
end
```

I won't enqueue a new `UpdateMetricsJob` job if one already exists in my Resque queue

**Comment by jmettraux** [comment]
If you allow me:

```ruby
require 'rufus-scheduler'

scheduler = Rufus::Scheduler.singleton

scheduler.every '10m', tag: 'UpdateMetricsJob' do

  UpdateMetricsJob.perform_later unless \
    Resque
      .peek(:default, 0, 1000)
      .find { |job| job['args'][0]['job_class'] == 'UpdateMetricsJob' }
end 
```
