### ISSUE TITLE
singleton option doesn't work well for elastic-beanstalk deployment

### ISSUE THREAD

**Issue by pelaprat** [jmettraux/rufus-scheduler#208]
I'm struggling to deploy a rufus-scheduler to my RoR application via ElasticBeanstalk.

Following the docs, I instantiate a rufus-scheduler in an initializer (`config/initializers/scheduler.rb`). I've tried to instantiate it as a constant, singleton, and global variable but, because the initialization process runs four times, I get all sorts of weird effects (partly described [here](http://stackoverflow.com/questions/37551004/elastic-beanstalk-and-rails-initializing-multiple-times)).

In my app, I've created a UI to create, edit and delete scheduled jobs. Sometimes, the UI says there's a Scheduler running. And sometimes it doesn't. I have no idea what's going on. Again, I think this is partly related to the initialization process getting run four times. I've tried using rufus-scheduler's `lockfile` option – doesn't help.

Any ideas?

**Comment by jmettraux** [comment]
Hello,

The title would be better as "singleton option doesn't work for elastic-beanstalk deployement".

A possible explanation would be that all your instances have their own ```/tmp/.rufus-scheduler.lock``` so that no locking at all occurs. That's easy to test.

the ```:lockfile``` system is meant for forking deployments, where a single host runs an app in multiple processes and the rufus-scheduler of a single process must stay. Your case seems different, multiple hosts with each one Ruby process. ```:lockfile``` falls short in those cases please read the following documentation:

https://github.com/jmettraux/rufus-scheduler#scheduler_lock
https://github.com/jmettraux/rufus-scheduler#advanced-lock-schemes

You then have to build your own locking mechanism and point rufus-scheduler to it.

Meilleures salutations.

**Comment by jmettraux** [comment]
(closing the issue but not the conversation)

**Comment by pelaprat** [comment]
Bonjour!

We capped the number of instances to 1, so we know there's only one instance running. It looks like the multiple initializations is [just an apache thing, maybe?](http://stackoverflow.com/a/6450015/6405075) 

I also tried the rake tasks approach referred to in the link above, but that won't work for us since the app UI enables users to create, edit, update jobs.

To try to debug what's going on, we've added info to the GUI for creating, editing, or updating jobs that shows the `object_id` for the Scheduler. 50% of the time the page shows a legit object_id that belongs to an instance, and 50% of the time it shows the object_id is 8, which I guess means there is no instance for that variable.

![screen shot 2016-06-02 at 4 12 06 pm](https://cloud.githubusercontent.com/assets/3650979/15761298/062f9d6c-28dd-11e6-90c0-b531cc5e6ef8.png)


![screen shot 2016-06-02 at 4 12 32 pm](https://cloud.githubusercontent.com/assets/3650979/15761304/0a6959a4-28dd-11e6-9155-1fa0d6b9cb06.png)

You could reload the page for 15 minutes and get one of these two pages...

**Comment by jmettraux** [comment]
@pelaprat wrote:
> We capped the number of instances to 1, so we know there's only one instance running.

One rufus-scheduler instance per Ruby process right?

As I wrote in my first answer, I suspect you have multiple processes on multiple hosts and those multiple hosts do not share the same ```/tmp```. But I cannot tell for sure since I have no access to your system.

**Comment by pelaprat** [comment]
It seems like the right thing to do is write a custom locking mechanism that uses the RDS instance behind our EB environment.

**Comment by jmettraux** [comment]
Yes!

**Comment by jmettraux** [comment]
If you only do cron jobs, could something like this help: https://medium.com/@joelennon/running-cron-jobs-on-amazon-web-services-aws-elastic-beanstalk-a41d91d1c571#.nrsq9dknk

**Comment by pelaprat** [comment]
We don't do only cron jobs. Let's give the RDS-backed locking mechanism a go and see how that works. Thanks!

**Comment by jmettraux** [comment]
You're welcome!

**Comment by pelaprat** [comment]
Well, that's not working either.

I think the core of the issue is about how apps get deployed and run in EB>

The initialization process is run four times during EB deployment. So that means four Scheduler instances get created during the initialization process. The first instance is created and sets the lock to `true`, so the last three instances are created but down.

Even if I create the Scheduler outside of the initialization process, I always get two Schedulers. This is because – it appears – the RoR app is running on two processes after it is initialized. This is evident in the `production.log` file for the deployed instance, where I see two different process ids for any given request. E.g.:

```
I, [2016-06-06T13:29:50.451070 #32327]  INFO -- : Started GET "/tasks" for 24.14.55.218 at 2016-06-06 13:29:50 -0400

...

I, [2016-06-06T13:29:48.862964 #32323]  INFO -- : Started GET "/tasks" for 24.14.55.218 at 2016-06-06 13:29:48 -0400
```

So I'm really not sure what to do now.

**Comment by jmettraux** [comment]
> Even if I create the Scheduler outside of the initialization process, I always get two Schedulers.

Are you trying to say that if you create the Scheduler inside of the initialization process you get two scheduler instances as well?

Now that you seem to have a custom scheduler lock that works between hosts, you could take inspiration from the rufus-scheduler vanilla lockfile implementation and pad your scheduler lock so that only a single scheduler instance gets started. One scheduler lock implementation, two cases addressed.

**Comment by pelaprat** [comment]
> Are you trying to say that if you create the Scheduler inside of the initialization process you get two scheduler instances as well?

Actually, the logs show that four Scheduler instances are created. It's just that three of them are down. But instances of the Schedulers are made.

> Now that you seem to have a custom scheduler lock that works between hosts, you could take inspiration from the rufus-scheduler vanilla lockfile implementation and pad your scheduler lock so that only a single scheduler instance gets started. One scheduler lock implementation, two cases addressed.

I tried this, and the problem isn't fixed since there seems to always be two RoR processes running for a single host of a single instance of my application. So as the user interacts with the application, the logs show that either one of two ruby processes is getting used (that's what the `production.log` info above shows. Notice the two different numbers after the `#` sign in the log).

I think the core issue here is an ElasticBeanstalk quirk/feature that I don't understand...

**Comment by jmettraux** [comment]
It simply seems that the package you use for Rails on ElasticBeanstalk is using something like Unicorn or Passenger, a server that forks multiple (in your case 2) ruby processes to serve requests. You'd have to identify what server your app runs on (the head of the logs usually tell).

Maybe you should rethink your architecture and instead of having a single Rails app that does everything, you could have the Rails app that does the web serving and a Ruby app that does the scheduling (more like a worker). For instance, the Heroku guys show how to split an app between web, worker and clock (scheduler), see https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes (they use https://github.com/tomykaira/clockwork which comes from one of their developers).

**Comment by pelaprat** [comment]
We're using Puma as our web server, but I think you're right, we need to re-think the architecture and separate the web app from another app to manage the scheduling. The problem clearly isn't Rufus Scheduler :)

Thanks!
