### ISSUE TITLE
"in" style scheduling throws timzone warning

### ISSUE THREAD

**Issue by hummingV** [jmettraux/rufus-scheduler#211]
Hi,
"in" style scheduling throws the following timezone warning
`/home/kaung/.rvm/gems/jruby-1.7.19/gems/rufus-scheduler-3.2.1/lib/rufus/scheduler/zotime.rb:48 warning: Unrecognized time zone: 2s`
It seems to be a bug?
```
bash> irb
jruby-1.7.19 :001 > require 'rufus/scheduler'
jruby-1.7.19 :002 > scheduler = Rufus::Scheduler.new(:max_work_threads => 1)
jruby-1.7.19 :003 > scheduler.in "2s" do
jruby-1.7.19 :004 >     print 'hello'
jruby-1.7.19 :005?>   end
/home/kaung/.rvm/gems/jruby-1.7.19/gems/rufus-scheduler-3.2.1/lib/rufus/scheduler/zotime.rb:48 warning: Unrecognized time zone: 2s
 => "in_1468435683.801_0.0_651100072" 
jruby-1.7.19 :006 > hello
```

**Comment by jmettraux** [comment]
Hello,

I wouldn't say it's a bug since it is working (`hello` getting printed).

I tried on `jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_60-b27 +jit [darwin-x86_64]` and there was no warning.

I think it was fixed in https://github.com/jruby/jruby/issues/2759

Best regards.

**Comment by hummingV** [comment]
Thanks, I confirmed that warning message is not reproducible in 1.7.22
