### ISSUE TITLE
rufus-scheduler process cannot be terminated

### ISSUE THREAD

**Issue by slashd0t** [jmettraux/rufus-scheduler#282]
Hi guys,
I want to terminate or stop the running process of rufus scheduler so I run the top command. See below:
```
$ top -bc | grep rufus-scheduler
17317 armando    20   0   22004   1092    996 S   0.0  0.0   0:00.00 grep --color=auto rufus-scheduler
17317 armando    20   0   22004   1092    996 S   0.0  0.0   0:00.00 grep --color=auto rufus-scheduler
```

So I found the 17317, I tried to kill it using command: `kill -9 17317` however the rufus scheduler was still active.

Any ideas/suggestions on how to force terminate the rufus scheduler background process?

**Comment by jmettraux** [comment]
Hello,

as you can see, the process 17317 is actually a "grep" process. If you're trying to locate the Ruby process hosting the rufus-scheduler thread, you might have more luck doing `ps aux | grep ruby`.

I am closing the issue since it is not a rufus-scheduler issue but a general unix/shell issue. Feel free to ask further questions, I'll help the best I can.

Best regards.
