### ISSUE TITLE
Getting time when cron job is invoked

### ISSUE THREAD

**Issue by kazhian** [jmettraux/rufus-scheduler#321]
I created a cron job which generates a report. In report i want to include the job time, instead of calculating current time.

So, I passed job parameter to the code block. When I use job.last_time it gives me the time. But how to find the time zone from it?

```ruby
Rufus::Scheduler.new.cron '* * * * *' do |job|
    puts "#{job.last_time.zone}"
end
```

But the zone is printed as 'Etc - UTC'. Why it displays two zones?

**Comment by jmettraux** [comment]
Hello,

"Etc" is not a time zone, it's an [area](https://en.wikipedia.org/wiki/Tz_database#Area). See also the [list of database timezones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

Closing since it's not a Rufus-Scheduler issue but it's related to how your system is set.

Best regards.

**Comment by jmettraux** [comment]
Other ways to play with it:


```ruby
require 'rufus-scheduler'

s = Rufus::Scheduler.new

s.cron '*/3 * * * * *' do |job|
  puts "-"
  puts "#{job.last_time}"
  puts "#{job.last_time.zone}"
  puts "#{job.last_time.zone.name}"
  puts "#{job.last_time.zone.abbreviation}"
  puts "#{job.last_time.zone.canonical_zone}"
  puts "#{job.last_time.zone.canonical_identifier}"
  puts "#{job.last_time.zone.friendly_identifier}"
  puts "#{job.last_time.to_t}"
  puts "#{job.last_time.to_t.zone}"
end

s.join
```

**Comment by kazhian** [comment]
Thank you !!
