### ISSUE TITLE
Rails reloader

### ISSUE THREAD

**Issue by jjb** [jmettraux/rufus-scheduler#326]
I recently discovered the rails reloader: https://github.com/jjb/ruby-clock/commit/cbe01a75260eb954a441d8d844c5c3ab1c5e8ac0

I wonder if it's worth suggesting in the rufus-scheduler docs too?

Thing is I don't really know typical use cases of rufus in rails outside of ruby-clock. But I _think_ either the executor or reloader would be beneficial for some of them.

p.s. I saw this nice clock in London the other day

![252773D6-96A9-430C-8A8C-B58E29A6ED62_1_105_c](https://user-images.githubusercontent.com/6097/133777860-1a368da5-132b-46b8-8ecb-51a83d39c5d7.jpeg)

![D81FEFA3-CCB7-4536-B93F-FD93FFE2D78D_1_105_c](https://user-images.githubusercontent.com/6097/133777877-50f7b5e3-bd65-4d6e-baa6-1fa0d0e5d72d.jpeg)

**Comment by jmettraux** [comment]
Thanks for the clock pictures! You're lucky to be in London, I'd love to walk its parks. Yes, "Fugit" takes its name from the old "Tempus Fugit" adage :-)

Rails is a beginner's magnet and thus such changes will have an impact on rufus-scheduler because it will be rufus' fault :-( I'd wait until the first case shows up and then learn from it and update the documentation... If you feel like you can give us a headstart by adding a piece of documentation to the rufus-scheduler readme, that would be grand, pull-request welcome! Else if you give me a pointer to a piece of Ruby-Clock documentation, that would be cool too (and would direct traffic to your work).

Kind regards

**Comment by jjb** [comment]
Okay, made a PR with a simple note for the time being.

**Comment by jmettraux** [comment]
Thanks a lot!
