### ISSUE TITLE
Instances don't work after fork

### ISSUE THREAD

**Issue by brauliobo** [jmettraux/rufus-scheduler#346]
In the code below:
```
[1] pry(main)> s=Rufus::Scheduler.new; fork{ s.every('1s'){ puts 'blah' } }
=> 176616
```
`blah` will never be printed. If the instance is created inside the fork block then it works.

**Comment by jmettraux** [comment]
This is as expected.

**Comment by brauliobo** [comment]
just curious, why?

**Comment by jmettraux** [comment]
> just curious, why? 

Because rufus-scheduler [uses threads](https://github.com/jmettraux/rufus-scheduler#non-features).

> maybe an error should be raised?

You're the first person in 10 or more years to ask for that. If more people were clamouring for it, I would consider that. 
.

People usually go for [sidekiq-cron](https://github.com/sidekiq-cron/sidekiq-cron), [solid_queue](https://github.com/rails/solid_queue), [whenever](https://github.com/javan/whenever), or others. Maybe one of those is what you are looking for.
