### ISSUE TITLE
frequency checking very slow

### ISSUE THREAD

**Issue by yoyos** [jmettraux/rufus-scheduler#89]
Hi, first great job with this gem :)

I just wanted to talk about the CronLine frequency method.
First i used frequency but after this I used previous_time.

For example if I do :

```
for i in 0..5000
  cron_line = Rufus::Scheduler.parse("*/5 * * * *")
  puts cron_line.frequency
end
```

It takes just forever to execute even one line.

And if I do : 

```
for i in 0..5000
  cron_line = Rufus::Scheduler.parse("*/5 * * * *")
  puts cron_line.next_time.to_i - cron_line.previous_time.to_i
end
```

It takes a few second for the same result.

If I want to compare previous, current and next times, I can't use the frequency method then ? What is this method for ?

My goal is to have only one job reading database for many jobs to execute or not, depending on last_checked_time < previous_time

What is the best way to achieve that if it were for you ?

Thanks !

**Comment by ketan** [comment]
It appears that the cost of computing the frequency is directly proportional to the number of occurrences of the cron during the year.

I did a quick profiler run and found 2 places where we could optimize on computing the frequency of `*/2 * * * *` (pretty close to the worst case)

Changing the implementation of [parse_item](https://github.com/jmettraux/rufus-scheduler/blob/e514bd5a0fdde49240f3b5f48cfa2853b282be3a/lib/rufus/scheduler/cronline.rb#L343-L354) to return a `Set` instead of an `Array` will cause the `include?` operation in `sub_match?` run a whole lot faster

```
    def parse_item(item, min, max)

      return nil if item == '*'

      r = item.split(',').map { |i| parse_range(i.strip, min, max) }.flatten

      raise ArgumentError.new(
        "found duplicates in #{item.inspect}"
      ) if r.uniq.size < r.size

      Set.new(r) # the optimization
    end
```

Here is the benchmark for `*/2 * * * *`

```
% ruby benchmark-rufus-scheduler.rb
              user     system      total        real
regular:   78.480000   0.210000  78.690000 ( 78.747986)
optimized: 33.920000   0.180000  34.100000 ( 34.154923)
```

There are a bunch of tests that fail with this change, but I'm happy to fix them if you're OK with this change.

**Comment by jmettraux** [comment]
Hello,

sounds interesting. Could you please open a new issue and state which Ruby you're benchmarking against?

Thanks in advance,

John
